name: build and push docker image
on:
  workflow_dispatch:
  push:
    branches: [main, stable-feature-dockerfile ] 



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: auswar
          password: ${{ secrets.DOCKER_HUB_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: auswar/team2_project:latest

  deploy:
    environment: NASA_API_KEY
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: SSH into AWS EC2 instance
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST_IP }}
            username: ${{ secrets.AWS_LOGIN_NAME }}
            password: ${{ secrets.AWS_LOGIN_PASSWORD }}
            script: |
              
              # Pull Docker image from registry
              
              echo "hello world!"

              # kill old container
                docker stop $(docker ps -a -q)
                # Remove all containers
                docker rm $(docker ps -a -q)

                # Remove all images
                docker rmi $(docker images -q)
                docker stop server
                docker rm server

              docker pull auswar/team2_project:latest
              
              # Run Docker container
                docker run -d -p 80:5000 -e NASA_API_KEY=${{ secrets.NASA_API_KEY }} --name server auswar/team2_project:latest
              docker ps
