[tool.poetry]
name = "team2-proj"
version = "0.1.0"
description = ""
authors = ["ZacSchepis <schezack@isu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
quart = "^0.19.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
